# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/refs/heads/master/schema/config.json

git:
  pagers:
    - externalDiffCommand: difft --color=always

customCommands:
  - key: "<c-g>"
    context: "files"
    description: "Autogenerate commit message from staged diff (Gemini)"
    command: '~/.config/lazygit/gen-commit-msg.py'
    loadingText: "Generating commit message..."
    output: terminal
