#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["google-genai"]
# ///
"""Generate a commit message for staged changes via Gemini."""

from __future__ import annotations

import fnmatch
import os
import pathlib
import subprocess
import sys

from google import genai
from google.genai import types

SECRETS_FILE = pathlib.Path.home() / ".config" / "secrets.env"


def load_secrets(path: pathlib.Path) -> None:
    if not path.is_file():
        return
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export ") :]
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value

MODEL = "gemini-3.1-flash-lite"
MAX_DIFF_LINES = 1000
LOCK_PATTERNS = [
    "*.lock",
    "*.lockb",
    "*-lock.json",
    "*-lock.yaml",
    "*-lock.yml",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Cargo.lock",
    "poetry.lock",
    "pixi.lock",
    "uv.lock",
    "Pipfile.lock",
    "composer.lock",
    "Gemfile.lock",
    "go.sum",
    "*.min.js",
    "*.min.css",
]

SYSTEM_PROMPT = """
# Task
Write a single sentence commit message for the diff the user provides.

# Guidelines
- Follow conventional commits
- When referencing file names or identifiers in code, put them in `backticks`
- The message must use active language and start with a verb in present tense
- do not use generic words like "code", use the domain language of the code instead
- instead of "and" just use commas: "fix A, refactor B"
- Be as specific as possible! E.g., Instead of "update filtering logic", say: "filter for historical flag"

# Examples
<good>
- fix: make `MyReranker` agnostic to input order
- feat: add `DenseRetriever` embedding search
- chore: fix deprecation warning in `pydantic_ai.Model.call`
</good>

<bad>
- remove unused dataframe library

You write concise, conventional git commit messages.

Rules:
- Output ONLY the commit message. No code fences, no preamble, no trailing notes.
- Subject line: imperative mood, lowercase, <=72 chars, no trailing period.
- Prefer one logical message describing the whole staged change.

Example:
feat(scope): terse comment in present tense
"""


def run(cmd: list[str]) -> str:
    return subprocess.check_output(cmd, text=True)


def is_autogenerated(path: str) -> bool:
    name = os.path.basename(path)
    return any(fnmatch.fnmatch(name, p) or fnmatch.fnmatch(path, p) for p in LOCK_PATTERNS)


def build_prompt() -> str | None:
    name_status = run(["git", "diff", "--cached", "--name-status"]).strip()
    if not name_status:
        return None

    sections: list[str] = [f"<files>\n{name_status}\n</files>"]

    for line in name_status.splitlines():
        parts = line.split("\t")
        status, path = parts[0], parts[-1]
        if is_autogenerated(path):
            sections.append(f"<diff path=\"{path}\" status=\"{status}\">\n[skipped: autogenerated/lock file]\n</diff>")
            continue

        diff = run(["git", "diff", "--cached", "--", path])
        line_count = diff.count("\n")
        if line_count > MAX_DIFF_LINES:
            sections.append(
                f"<diff path=\"{path}\" status=\"{status}\">\n[skipped: {line_count} lines > {MAX_DIFF_LINES}]\n</diff>"
            )
            continue
        sections.append(f"<diff path=\"{path}\" status=\"{status}\">\n{diff}</diff>")

    return "\n\n".join(sections)


def main() -> int:
    prompt = build_prompt()
    if prompt is None:
        print("No staged changes.", file=sys.stderr)
        return 1

    load_secrets(SECRETS_FILE)
    api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        print(f"GEMINI_API_KEY not set (checked env and {SECRETS_FILE}).", file=sys.stderr)
        return 2

    client = genai.Client(api_key=api_key)
    response = client.models.generate_content(
        model=MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
            thinking_config=types.ThinkingConfig(thinking_level="minimal"),
        ),
    )

    message = (response.text or "").strip()
    if not message:
        print("Empty response from model.", file=sys.stderr)
        return 3

    # Emit a single line so lazygit's `runCommand` can use it as the
    # initial value of the commit-message prompt (it rejects multi-line output).
    print(message.splitlines()[0])
    return 0


if __name__ == "__main__":
    sys.exit(main())
