#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["google-genai"]
# ///
"""Generate a commit message for staged changes via Gemini."""

from __future__ import annotations

import fnmatch
import os
import pathlib
import subprocess
import sys

from google import genai
from google.genai import types

SECRETS_FILE = pathlib.Path.home() / ".config" / "secrets.env"


def load_secrets(path: pathlib.Path) -> None:
    if not path.is_file():
        return
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export ") :]
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value

MODEL = "gemini-3.1-flash-lite"
MAX_DIFF_LINES = 1000
LOCK_PATTERNS = [
    "*.lock",
    "*.lockb",
    "*-lock.json",
    "*-lock.yaml",
    "*-lock.yml",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Cargo.lock",
    "poetry.lock",
    "pixi.lock",
    "uv.lock",
    "Pipfile.lock",
    "composer.lock",
    "Gemfile.lock",
    "go.sum",
    "*.min.js",
    "*.min.css",
]

SYSTEM_PROMPT = """You write concise, conventional git commit messages.

Rules:
- Output ONLY the commit message. No code fences, no preamble, no trailing notes.
- Subject line: imperative mood, lowercase, <=72 chars, no trailing period.
- If the change is non-trivial, add a blank line and a short body (wrapped ~72 chars) explaining the *why*, not the *what*.
- Prefer one logical message describing the whole staged change.

Example:
feat(scope): terse comment in present tense
"""


def run(cmd: list[str]) -> str:
    return subprocess.check_output(cmd, text=True)


def is_autogenerated(path: str) -> bool:
    name = os.path.basename(path)
    return any(fnmatch.fnmatch(name, p) or fnmatch.fnmatch(path, p) for p in LOCK_PATTERNS)


def build_prompt() -> str | None:
    name_status = run(["git", "diff", "--cached", "--name-status"]).strip()
    if not name_status:
        return None

    sections: list[str] = [f"<files>\n{name_status}\n</files>"]

    for line in name_status.splitlines():
        parts = line.split("\t")
        status, path = parts[0], parts[-1]
        if is_autogenerated(path):
            sections.append(f"<diff path=\"{path}\" status=\"{status}\">\n[skipped: autogenerated/lock file]\n</diff>")
            continue

        diff = run(["git", "diff", "--cached", "--", path])
        line_count = diff.count("\n")
        if line_count > MAX_DIFF_LINES:
            sections.append(
                f"<diff path=\"{path}\" status=\"{status}\">\n[skipped: {line_count} lines > {MAX_DIFF_LINES}]\n</diff>"
            )
            continue
        sections.append(f"<diff path=\"{path}\" status=\"{status}\">\n{diff}</diff>")

    return "\n\n".join(sections)


def main() -> int:
    prompt = build_prompt()
    if prompt is None:
        print("No staged changes.", file=sys.stderr)
        return 1

    load_secrets(SECRETS_FILE)
    api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        print(f"GEMINI_API_KEY not set (checked env and {SECRETS_FILE}).", file=sys.stderr)
        return 2

    client = genai.Client(api_key=api_key)
    response = client.models.generate_content(
        model=MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
            thinking_config=types.ThinkingConfig(thinking_level="minimal"),
        ),
    )

    message = (response.text or "").strip()
    if not message:
        print("Empty response from model.", file=sys.stderr)
        return 3

    return confirm_and_commit(message)


BOLD = "\033[1m"
DIM = "\033[2m"
CYAN = "\033[36m"
GREEN = "\033[32m"
RESET = "\033[0m"


def confirm_and_commit(message: str) -> int:
    sep = "─" * 60
    print(f"\n{CYAN}{sep}{RESET}")
    print(f"{BOLD}Generated commit message{RESET}")
    print(f"{CYAN}{sep}{RESET}")
    print(message)
    print(f"{CYAN}{sep}{RESET}")
    print(f"{DIM}[{RESET}{GREEN}y{RESET}{DIM}]es commit  [{RESET}e{DIM}]dit then commit  [{RESET}n{DIM}]o abort{RESET}")

    while True:
        try:
            choice = input("> ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print("\naborted.")
            return 130
        if choice in ("y", ""):
            subprocess.check_call(["git", "commit", "-m", message])
            return 0
        if choice == "e":
            subprocess.check_call(["git", "commit", "-e", "-m", message])
            return 0
        if choice == "n":
            print("aborted.")
            return 1


if __name__ == "__main__":
    sys.exit(main())
